// Some of the Knockout examples use this data
var comps = [{
    "transport": [
      {
        "name": "light_aerotransit",
        "image": "/img/engine/standard_engine.gif",
        "size": 3,
		"agility": 1,
		"mobility":250,
		"armor":0,
		"upkeep":10,
		"time":800,
		"titanium":400,
		"copper":500,
		"iron":250,
		"aluminium":250,
		"silicon":0,
		"uranium":500,
		"nitrogen":500,
		"hydrogen":0	
      },
      {
          "name": "medium_aerotransit",
          "image": "/img/engine/standard_engine.gif",
          "size": 8,
  		"agility": 3,
  		"mobility":500,
  		"armor":0,
  		"upkeep":10,
  		"time":1500,
  		"titanium":550,
  		"copper":500,
  		"iron":500,
  		"aluminium":500,
  		"silicon":0,
  		"uranium":1000,
  		"nitrogen":700,
  		"hydrogen":0	
        },{
        "name": "armored_troop_carrier",
        "image": "/img/engine/standard_engine.gif",
        "size": 10,
		"agility": 4,
		"mobility":1000,
		"armor":0,
		"upkeep":10,
		"time":2500,
		"titanium":200,
		"copper":750,
		"iron":750,
		"aluminium":7500,
		"silicon":0,
		"uranium":1500,
		"nitrogen":800,
		"hydrogen":250	
      },{
          "name": "hovercraft_cw1_1",
          "image": "/img/engine/standard_engine.gif",
          "size": 15,
  		"agility": 5,
  		"mobility":1200,
  		"armor":0,
  		"upkeep":10,
  		"time":5000,
  		"titanium":100,
  		"copper":750,
  		"iron":1000,
  		"aluminium":1000,
  		"silicon":0,
  		"uranium":2000,
  		"nitrogen":900,
  		"hydrogen":500	
        },{
            "name": "hovercraft_cw1_2",
            "image": "/img/engine/standard_engine.gif",
            "size": 15,
    		"agility": 5,
    		"mobility":1600,
    		"armor":0,
    		"upkeep":10,
    		"time":10000,
    		"titanium":200,
    		"copper":1500,
    		"iron":2000,
    		"aluminium":2000,
    		"silicon":0,
    		"uranium":4000,
    		"nitrogen":1800,
    		"hydrogen":100	
          },{
              "name": "air_transporter",
              "image": "/img/engine/standard_engine.gif",
              "size": 18,
      		"agility": 6,
      		"mobility":1900,
      		"armor":0,
      		"upkeep":10,
      		"time":5000,
      		"titanium":200,
      		"copper":600,
      		"iron":1100,
      		"aluminium":340,
      		"silicon":0,
      		"uranium":200,
      		"nitrogen":700,
      		"hydrogen":500	
            },{
            "name": "medium_air_transporter",
                "image": "/img/engine/standard_engine.gif",
                "size": 23,
        		"agility": 7,
        		"mobility":2100,
        		"armor":0,
        		"upkeep":10,
        		"time":6000,
        		"titanium":300,
        		"copper":1200,
        		"iron":2500,
        		"aluminium":250,
        		"silicon":0,
        		"uranium":2000,
        		"nitrogen":800,
        		"hydrogen":400	
              },{
                  "name": "amphibious_vehicle",
                  "image": "/img/engine/standard_engine.gif",
                  "size": 24,
          		"agility": 8,
          		"mobility":2700,
          		"armor":0,
          		"upkeep":10,
          		"time":14000,
          		"titanium":1000,
          		"copper":1400,
          		"iron":6020,
          		"aluminium":1500,
          		"silicon":0,
          		"uranium":4000,
          		"nitrogen":1800,
          		"hydrogen":1200	
                },{
                  "name": "gamma_air_transporter",
                  "image": "/img/engine/standard_engine.gif",
                  "size": 24,
          		"agility": 8,
          		"mobility":2200,
          		"armor":0,
          		"upkeep":10,
          		"time":7000,
          		"titanium":500,
          		"copper":1200,
          		"iron":3010,
          		"aluminium":750,
          		"silicon":0,
          		"uranium":2000,
          		"nitrogen":900,
          		"hydrogen":600	
                },{
                "name": "ozo_agro_tractor",
                    "image": "/img/engine/standard_engine.gif",
                    "size": 48,
            		"agility": 15,
            		"mobility":5875,
            		"armor":350,
            		"upkeep":10,
            		"time":21420,
            		"titanium":400,
            		"copper":500,
            		"iron":250,
            		"aluminium":250,
            		"silicon":0,
            		"uranium":500,
            		"nitrogen":500,
            		"hydrogen":0	
                  }, {
                "name": "moso_navigator",
                "image": "/img/engine/standard_engine.gif",
                "size": 24,
        		"agility": 8,
        		"mobility":2800,
        		"armor":0,
        		"upkeep":10,
        		"time":7000,
        		"titanium":500,
        		"copper":700,
        		"iron":3010,
        		"aluminium":750,
        		"silicon":0,
        		"uranium":2000,
        		"nitrogen":900,
        		"hydrogen":600	
              }
	 ],
    "projectile": [
 	  {
          "name": "eagle_i",
          "image": "/img/engine/standard_engine.gif",
          "size": 9,
  		"attack": 35,
  		"aim":40,
  		"upkeep":10,
  		"time":7200,
  		"titanium":9000,
  		"copper":0,
  		"iron":0,
  		"aluminium":0,
  		"silicon":5000,
  		"uranium":500,
  		"nitrogen":0,
  		"hydrogen":500	
        },{
            "name": "air_rifle",
            "image": "/img/engine/standard_engine.gif",
            "size": 10,
    		"attack": 33,
    		"aim":45,
    		"upkeep":10,
    		"time":7200,
    		"titanium":5000,
    		"copper":590,
    		"iron":0,
    		"aluminium":0,
    		"silicon":5000,
    		"uranium":0,
    		"nitrogen":0,
    		"hydrogen":25000	
          },{
              "name": "crusher",
              "image": "/img/engine/standard_engine.gif",
              "size": 9,
      		"attack": 45,
      		"aim":25,
      		"upkeep":10,
      		"time":7200,
      		"titanium":650,
      		"copper":300,
      		"iron":0,
      		"aluminium":500,
      		"silicon":4000,
      		"uranium":0,
      		"nitrogen":5000,
      		"hydrogen":0	
            },{
            "name": "eagle_ii",
            "image": "/img/engine/standard_engine.gif",
            "size": 11,
    		"attack": 40,
    		"aim":50,
    		"upkeep":10,
    		"time":7200,
    		"titanium":9876,
    		"copper":0,
    		"iron":500,
    		"aluminium":0,
    		"silicon":5000,
    		"uranium":0,
    		"nitrogen":5000,
    		"hydrogen":0	
              },{
              "name": "eagle_ii_h",
              "image": "/img/engine/standard_engine.gif",
              "size": 10,
      		"attack": 40,
      		"aim":60,
      		"upkeep":10,
      		"time":9876,
      		"titanium":0,
      		"copper":0,
      		"iron":50,
      		"aluminium":0,
      		"silicon":5000,
      		"uranium":0,
      		"nitrogen":4000,
      		"hydrogen":0	
            },{
            "name": "eagle_iii_h",
                "image": "/img/engine/standard_engine.gif",
                "size": 22,
        		"attack": 117,
        		"aim":52,
        		"upkeep":10,
        		"time":53856,
        		"titanium":73872,
        		"copper":0,
        		"iron":0,
        		"aluminium":3740,
        		"silicon":37400,
        		"uranium":0,
        		"nitrogen":29920,
        		"hydrogen":0	
              },{
                  "name": "assault_rifle_g_iii",
                  "image": "/img/engine/standard_engine.gif",
                  "size": 7,
          		"attack": 40,
          		"aim":20,
          		"upkeep":10,
          		"time":7200,
          		"titanium":257,
          		"copper":0,
          		"iron":0,
          		"aluminium":0,
          		"silicon":3167,
          		"uranium":8167,
          		"nitrogen":167,
          		"hydrogen":0	
                },{
                "name": "light_machine_gun",
                    "image": "/img/engine/standard_engine.gif",
                    "size": 9,
            		"attack": 40,
            		"aim":30,
            		"upkeep":10,
            		"time":7200,
            		"titanium":500,
            		"copper":0,
            		"iron":0,
            		"aluminium":0,
            		"silicon":4167,
            		"uranium":167,
            		"nitrogen":167,
            		"hydrogen":0	
                  },{
                      "name": "mp_92",
                      "image": "/img/engine/standard_engine.gif",
                      "size": 5,
              		"attack": 35,
              		"aim":15,
              		"upkeep":10,
              		"time":7200,
              		"titanium":980,
              		"copper":500,
              		"iron":0,
              		"aluminium":0,
              		"silicon":3000,
              		"uranium":300,
              		"nitrogen":5000,
              		"hydrogen":0	
                    },{
                    "name": "heavy_machine_gun",
                        "image": "/img/engine/standard_engine.gif",
                        "size": 9,
                		"attack": 45,
                		"aim":25,
                		"upkeep":10,
                		"time":14400,
                		"titanium":1000,
                		"copper":0,
                		"iron":0,
                		"aluminium":0,
                		"silicon":8334,
                		"uranium":334,
                		"nitrogen":334,
                		"hydrogen":0	
                      },{
                          "name": "sword",
                          "image": "/img/engine/standard_engine.gif",
                          "size": 10,
                  		"attack": 40,
                  		"aim":35,
                  		"upkeep":10,
                  		"time":7200,
                  		"titanium":400,
                  		"copper":0,
                  		"iron":0,
                  		"aluminium":0,
                  		"silicon":4167,
                  		"uranium":5167,
                  		"nitrogen":167,
                  		"hydrogen":0	
                        },{
                        "name": "tzoonamy",
                            "image": "/img/engine/standard_engine.gif",
                            "size": 11,
                    		"attack": 200,
                    		"aim":10,
                    		"upkeep":10,
                    		"time":7200,
                    		"titanium":50000,
                    		"copper":0,
                    		"iron":0,
                    		"aluminium":0,
                    		"silicon":5134,
                    		"uranium":9134,
                    		"nitrogen":134,
                    		"hydrogen":0	
                          },{
                              "name": "scimitar",
                              "image": "/img/engine/standard_engine.gif",
                              "size": 12,
                      		"attack": 155,
                      		"aim":15,
                      		"upkeep":10,
                      		"time":7200,
                      		"titanium":60000,
                      		"copper":0,
                      		"iron":0,
                      		"aluminium":400,
                      		"silicon":5000,
                      		"uranium":0,
                      		"nitrogen":0,
                      		"hydrogen":50000	
                            },{
                            "name": "hammer",
                                "image": "/img/engine/standard_engine.gif",
                                "size": 12,
                        		"attack": 160,
                        		"aim":18,
                        		"upkeep":10,
                        		"time":14400,
                        		"titanium":120000,
                        		"copper":0,
                        		"iron":0,
                        		"aluminium":800,
                        		"silicon":10000,
                        		"uranium":0,
                        		"nitrogen":0,
                        		"hydrogen":100000	
                              },{
                                  "name": "explosive_sling",
                                  "image": "/img/engine/standard_engine.gif",
                                  "size": 22,
                          		"attack": 112,
                          		"aim":50,
                          		"upkeep":10,
                          		"time":0,
                          		"titanium":0,
                          		"copper":0,
                          		"iron":0,
                          		"aluminium":0,
                          		"silicon":0,
                          		"uranium":0,
                          		"nitrogen":0,
                          		"hydrogen":0	
                                }
 	    ],
 	    "ion": [
     	  {
            "name": "annihilator",
            "image": "/img/engine/standard_engine.gif",
            "size": 20,
    		"attack": 45,
    		"aim":60,
    		"upkeep":10,
    		"time":8000,
    		"titanium":2500,
    		"copper":750,
    		"iron":300,
    		"aluminium":1940,
    		"silicon":2334,
    		"uranium":2334,
    		"nitrogen":2584,
    		"hydrogen":10000	
              },{
                  "name": "desintegrator",
                  "image": "/img/engine/standard_engine.gif",
                  "size": 18,
          		"attack": 50,
          		"aim":60,
          		"upkeep":10,
          		"time":4165,
          		"titanium":4300,
          		"copper":497,
          		"iron":0,
          		"aluminium":1456,
          		"silicon":8334,
          		"uranium":5334,
          		"nitrogen":8584,
          		"hydrogen":10000
     	      },{
     	            "name": "eradicator",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 18,
     	    		"attack": 55,
     	    		"aim":62,
     	    		"upkeep":10,
     	    		"time":8330,
     	    		"titanium":8600,
     	    		"copper":994,
     	    		"iron":2912,
     	    		"aluminium":16668,
     	    		"silicon":16668,
     	    		"uranium":17168,
     	    		"nitrogen":20000,
     	    		"hydrogen":20000	
     	      },{
     	            "name": "l_ion",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 15,
     	    		"attack": 40,
     	    		"aim":55,
     	    		"upkeep":10,
     	    		"time":1912,
     	    		"titanium":4300,
     	    		"copper":134,
     	    		"iron":0,
     	    		"aluminium":8596,
     	    		"silicon":12000,
     	    		"uranium":12000,
     	    		"nitrogen":12000,
     	    		"hydrogen":8500
     	      },{
     	            "name": "microsphere",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 20,
     	    		"attack": 40,
     	    		"aim":55,
     	    		"upkeep":10,
     	    		"time":4000,
     	    		"titanium":1000,
     	    		"copper":500,
     	    		"iron":250,
     	    		"aluminium":1150,
     	    		"silicon":1334,
     	    		"uranium":1334,
     	    		"nitrogen":1584,
     	    		"hydrogen":5000
     	      },{
     	            "name": "phaser",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 15,
     	    		"attack": 30,
     	    		"aim":50,
     	    		"upkeep":10,
     	    		"time":2000,
     	    		"titanium":500,
     	    		"copper":250,
     	    		"iron":250,
     	    		"aluminium":800,
     	    		"silicon":600,
     	    		"uranium":600,
     	    		"nitrogen":850,
     	    		"hydrogen":2500
     	      },{
     	            "name": "gopper",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 25,
     	    		"attack": 70,
     	    		"aim":70,
     	    		"upkeep":10,
     	    		"time":2149,
     	    		"titanium":9700,
     	    		"copper":431,
     	    		"iron":0,
     	    		"aluminium":351,
     	    		"silicon":0,
     	    		"uranium":0,
     	    		"nitrogen":250,
     	    		"hydrogen":10000
     	      },{
     	            "name": "sun_eye",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 20,
     	    		"attack": 55,
     	    		"aim":65,
     	    		"upkeep":10,
     	    		"time":4172,
     	    		"titanium":8500,
     	    		"copper":356,
     	    		"iron":0,
     	    		"aluminium":351,
     	    		"silicon":3667,
     	    		"uranium":3667,
     	    		"nitrogen":3917,
     	    		"hydrogen":9700
     	      }
     	    ],
 	    "laser": [
     	  {
	            "name": "dim_12",
 	            "image": "/img/engine/standard_engine.gif",
 	            "size": 4,
 	    		"attack": 6,
 	    		"aim":60,
 	    		"upkeep":10,
 	    		"time":1800,
 	    		"titanium":500,
 	    		"copper":500,
 	    		"iron":0,
 	    		"aluminium":0,
 	    		"silicon":584,
 	    		"uranium":344,
 	    		"nitrogen":334,
 	    		"hydrogen":8000
     	      },{
   	            "name": "laser_15_08",
 	            "image": "/img/engine/standard_engine.gif",
 	            "size": 4,
 	    		"attack": 6,
 	    		"aim":4,
 	    		"upkeep":10,
 	    		"time":1500,
 	    		"titanium":50,
 	    		"copper":250,
 	    		"iron":0,
 	    		"aluminium":500,
 	    		"silicon":67,
 	    		"uranium":67,
 	    		"nitrogen":67,
 	    		"hydrogen":0
     	      },{
   	            "name": "dim_12_2",
 	            "image": "/img/engine/standard_engine.gif",
 	            "size": 6,
 	    		"attack": 9,
 	    		"aim":70,
 	    		"upkeep":10,
 	    		"time":2500,
 	    		"titanium":1000,
 	    		"copper":600,
 	    		"iron":0,
 	    		"aluminium":50,
 	    		"silicon":834,
 	    		"uranium":334,
 	    		"nitrogen":334,
 	    		"hydrogen":0
     	      },{
   	            "name": "laser_pistol",
 	            "image": "/img/engine/standard_engine.gif",
 	            "size": 6,
 	    		"attack": 8,
 	    		"aim":45,
 	    		"upkeep":10,
 	    		"time":2000,
 	    		"titanium":50,
 	    		"copper":400,
 	    		"iron":0,
 	    		"aluminium":650,
 	    		"silicon":100,
 	    		"uranium":100,
 	    		"nitrogen":100,
 	    		"hydrogen":0
     	      },{
   	            "name": "rapid_flash",
 	            "image": "/img/engine/standard_engine.gif",
 	            "size": 7,
 	    		"attack": 13,
 	    		"aim":80,
 	    		"upkeep":10,
 	    		"time":3000,
 	    		"titanium":1500,
 	    		"copper":700,
 	    		"iron":0,
 	    		"aluminium":200,
 	    		"silicon":1100,
 	    		"uranium":350,
 	    		"nitrogen":350,
 	    		"hydrogen":4000
     	      },{
   	            "name": "kontinium_transfunkionator",
 	            "image": "/img/engine/standard_engine.gif",
 	            "size": 28,
 	    		"attack": 175,
 	    		"aim":50,
 	    		"upkeep":10,
 	    		"time":30600,
 	    		"titanium":18360,
 	    		"copper":6120,
 	    		"iron":0,
 	    		"aluminium":3060,
 	    		"silicon":10710,
 	    		"uranium":1530,
 	    		"nitrogen":1530,
 	    		"hydrogen":0
     	      },{
   	            "name": "silvermoon",
 	            "image": "/img/engine/standard_engine.gif",
 	            "size": 10,
 	    		"attack": 18,
 	    		"aim":85,
 	    		"upkeep":10,
 	    		"time":4000,
 	    		"titanium":2000,
 	    		"copper":800,
 	    		"iron":0,
 	    		"aluminium":300,
 	    		"silicon":1184,
 	    		"uranium":184,
 	    		"nitrogen":184,
 	    		"hydrogen":0
     	      },{
   	            "name": "white_dwarf",
 	            "image": "/img/engine/standard_engine.gif",
 	            "size": 13,
 	    		"attack": 100,
 	    		"aim":30,
 	    		"upkeep":10,
 	    		"time":4500,
 	    		"titanium":2500,
 	    		"copper":900,
 	    		"iron":0,
 	    		"aluminium":400,
 	    		"silicon":1584,
 	    		"uranium":334,
 	    		"nitrogen":334,
 	    		"hydrogen":1500
     	      },{
   	            "name": "darkness",
 	            "image": "/img/engine/standard_engine.gif",
 	            "size": 12,
 	    		"attack": 75,
 	    		"aim":40,
 	    		"upkeep":10,
 	    		"time":5000,
 	    		"titanium":3000,
 	    		"copper":1000,
 	    		"iron":0,
 	    		"aluminium":500,
 	    		"silicon":17500,
 	    		"uranium":250,
 	    		"nitrogen":250,
 	    		"hydrogen":0	
     	      },{
   	            "name": "starlight_x",
 	            "image": "/img/engine/standard_engine.gif",
 	            "size": 7,
 	    		"attack": 14,
 	    		"aim":50,
 	    		"upkeep":10,
 	    		"time":3000,
 	    		"titanium":100,
 	    		"copper":490,
 	    		"iron":0,
 	    		"aluminium":1000,
 	    		"silicon":67,
 	    		"uranium":67,
 	    		"nitrogen":67,
 	    		"hydrogen":0
     	      },{
   	            "name": "sunspot",
 	            "image": "/img/engine/standard_engine.gif",
 	            "size": 12,
 	    		"attack": 75,
 	    		"aim":42,
 	    		"upkeep":10,
 	    		"time":10000,
 	    		"titanium":6000,
 	    		"copper":2000,
 	    		"iron":0,
 	    		"aluminium":1000,
 	    		"silicon":3500,
 	    		"uranium":500,
 	    		"nitrogen":500,
 	    		"hydrogen":0
     	      },{
   	            "name": "superblaster",
 	            "image": "/img/engine/standard_engine.gif",
 	            "size": 10,
 	    		"attack": 25,
 	    		"aim":50,
 	    		"upkeep":10,
 	    		"time":4000,
 	    		"titanium":200,
 	    		"copper":234,
 	    		"iron":0,
 	    		"aluminium":250,
 	    		"silicon":167,
 	    		"uranium":167,
 	    		"nitrogen":167,
 	    		"hydrogen":0
     	      }
     	    ],
     	    "armor": [
        	  {
     	            "name": "genfood",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 2,
     	    		"armor": 125,
     	    		"launch": 256,
     	    		"upkeep":10,
     	    		"time":600,
     	    		"titanium":800,
     	    		"copper":0,
     	    		"iron":400,
     	    		"aluminium":0,
     	    		"silicon":27,
     	    		"uranium":27,
     	    		"nitrogen":27,
     	    		"hydrogen":0
        	      },{
       	            "name": "medkit",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 3,
     	    		"armor": 250,
     	    		"launch": 408,
     	    		"upkeep":10,
     	    		"time":900,
     	    		"titanium":1320,
     	    		"copper":0,
     	    		"iron":600,
     	    		"aluminium":0,
     	    		"silicon":40,
     	    		"uranium":40,
     	    		"nitrogen":40,
     	    		"hydrogen":0	
        	      },{
       	            "name": "mosomedic",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 3,
     	    		"armor": 427,
     	    		"launch": 992,
     	    		"upkeep":10,
     	    		"time":1633,
     	    		"titanium":2680,
     	    		"copper":0,
     	    		"iron":2280,
     	    		"aluminium":0,
     	    		"silicon":0,
     	    		"uranium":0,
     	    		"nitrogen":0,
     	    		"hydrogen":0
        	      },{
       	            "name": "large_medkit",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 4,
     	    		"armor": 375,
     	    		"launch": 752,
     	    		"upkeep":10,
     	    		"time":1200,
     	    		"titanium":2800,
     	    		"copper":0,
     	    		"iron":800,
     	    		"aluminium":0,
     	    		"silicon":54,
     	    		"uranium":54,
     	    		"nitrogen":54,
     	    		"hydrogen":0
        	      },{
       	            "name": "stimpack",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 5,
     	    		"armor": 500,
     	    		"launch": 960,
     	    		"upkeep":10,
     	    		"time":1500,
     	    		"titanium":3600,
     	    		"copper":0,
     	    		"iron":1200,
     	    		"aluminium":0,
     	    		"silicon":0,
     	    		"uranium":0,
     	    		"nitrogen":0,
     	    		"hydrogen":0
        	      },{
       	            "name": "vitagel",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 6,
     	    		"armor": 625,
     	    		"launch": 1440,
     	    		"upkeep":10,
     	    		"time":2000,
     	    		"titanium":5200,
     	    		"copper":0,
     	    		"iron":2000,
     	    		"aluminium":0,
     	    		"silicon":0,
     	    		"uranium":0,
     	    		"nitrogen":0,
     	    		"hydrogen":0
        	      },{
       	            "name": "traumapatch",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 7,
     	    		"armor": 750,
     	    		"launch": 1920,
     	    		"upkeep":10,
     	    		"time":2500,
     	    		"titanium":5600,
     	    		"copper":0,
     	    		"iron":4000,
     	    		"aluminium":0,
     	    		"silicon":0,
     	    		"uranium":0,
     	    		"nitrogen":0,
     	    		"hydrogen":0
        	      },{
       	            "name": "regenimplant",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 8,
     	    		"armor": 875,
     	    		"launch": 2400,
     	    		"upkeep":10,
     	    		"time":3000,
     	    		"titanium":6000,
     	    		"copper":0,
     	    		"iron":6000,
     	    		"aluminium":0,
     	    		"silicon":0,
     	    		"uranium":0,
     	    		"nitrogen":0,
     	    		"hydrogen":0
        	      },{
       	            "name": "exoskeleton",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 9,
     	    		"armor": 1050,
     	    		"launch": 1840,
     	    		"upkeep":10,
     	    		"time":3894,
     	    		"titanium":5120,
     	    		"copper":0,
     	    		"iron":4080,
     	    		"aluminium":0,
     	    		"silicon":0,
     	    		"uranium":0,
     	    		"nitrogen":0,
     	    		"hydrogen":0	
        	      },{
       	            "name": "medevac",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 9,
     	    		"armor": 1200,
     	    		"launch": 3968,
     	    		"upkeep":10,
     	    		"time":6532,
     	    		"titanium":10720,
     	    		"copper":0,
     	    		"iron":9120,
     	    		"aluminium":0,
     	    		"silicon":0,
     	    		"uranium":0,
     	    		"nitrogen":0,
     	    		"hydrogen":0
        	      },{
       	            "name": "mutagen",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 9,
     	    		"armor": 1100,
     	    		"launch": 1984,
     	    		"upkeep":10,
     	    		"time":3264,
     	    		"titanium":5360,
     	    		"copper":0,
     	    		"iron":4560,
     	    		"aluminium":0,
     	    		"silicon":0,
     	    		"uranium":0,
     	    		"nitrogen":0,
     	    		"hydrogen":0
        	      },{
       	            "name": "cy_prosthesis",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 10,
     	    		"armor": 1200,
     	    		"launch": 2112,
     	    		"upkeep":10,
     	    		"time":3132,
     	    		"titanium":6720,
     	    		"copper":0,
     	    		"iron":3840,
     	    		"aluminium":0,
     	    		"silicon":0,
     	    		"uranium":0,
     	    		"nitrogen":0,
     	    		"hydrogen":0
        	      },{
       	            "name": "imperial_mosomedic",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 18,
     	    		"armor": 2300,
     	    		"launch": 6071,
     	    		"upkeep":10,
     	    		"time":9994,
     	    		"titanium":16402,
     	    		"copper":0,
     	    		"iron":13954,
     	    		"aluminium":0,
     	    		"silicon":0,
     	    		"uranium":0,
     	    		"nitrogen":0,
     	    		"hydrogen":0
        	      }
        	    ],
         "shield": [
        	  {
     	            "name": "protective_mask",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 2,
     	    		"shield": 125,
     	    		"launch": 1264,
     	    		"agility":-3,
     	    		"upkeep":10,
     	    		"time":800,
     	    		"titanium":0,
     	    		"copper":400,
     	    		"iron":160,
     	    		"aluminium":2800,
     	    		"silicon":320,
     	    		"uranium":800,
     	    		"nitrogen":1200,
     	    		"hydrogen":640
        	      },{
       	            "name": "ballistic_helmet",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 10,
     	    		"shield": 500,
     	    		"launch": 1200,
     	    		"agility":-8,
     	    		"upkeep":10,
     	    		"time":900,
     	    		"titanium":0,
     	    		"copper":400,
     	    		"iron":200,
     	    		"aluminium":3200,
     	    		"silicon":334,
     	    		"uranium":934,
     	    		"nitrogen":134,
     	    		"hydrogen":800
        	      },{
       	            "name": "ballistic_armor",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 15,
     	    		"shield": 1100,
     	    		"launch": 4800,
     	    		"agility":-10,
     	    		"upkeep":10,
     	    		"time":3000,
     	    		"titanium":0,
     	    		"copper":800,
     	    		"iron":400,
     	    		"aluminium":12000,
     	    		"silicon":1467,
     	    		"uranium":6667,
     	    		"nitrogen":1067,
     	    		"hydrogen":1600
        	      },{
       	            "name": "ballistic_vest",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 15,
     	    		"shield": 1000,
     	    		"launch": 2400,
     	    		"agility":-9,
     	    		"upkeep":10,
     	    		"time":1500,
     	    		"titanium":0,
     	    		"copper":400,
     	    		"iron":200,
     	    		"aluminium":6000,
     	    		"silicon":734,
     	    		"uranium":3334,
     	    		"nitrogen":534,
     	    		"hydrogen":800
        	      },{
       	            "name": "kevlar_helmet",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 23,
     	    		"shield": 2000,
     	    		"launch": 3600,
     	    		"agility":-11,
     	    		"upkeep":10,
     	    		"time":3000,
     	    		"titanium":0,
     	    		"copper":400,
     	    		"iron":200,
     	    		"aluminium":9200,
     	    		"silicon":1534,
     	    		"uranium":4534,
     	    		"nitrogen":1334,
     	    		"hydrogen":800
        	      },{
       	            "name": "kevlar_armor",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 24,
     	    		"shield": 2350,
     	    		"launch": 25600,
     	    		"agility":-13,
     	    		"upkeep":10,
     	    		"time":4236,
     	    		"titanium":0,
     	    		"copper":800,
     	    		"iron":400,
     	    		"aluminium":12800,
     	    		"silicon":3067,
     	    		"uranium":106667,
     	    		"nitrogen":2667,
     	    		"hydrogen":1600
        	      },{
       	            "name": "power_helmet",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 24,
     	    		"shield": 2500,
     	    		"launch": 4160,
     	    		"agility":-14,
     	    		"upkeep":10,
     	    		"time":2391,
     	    		"titanium":0,
     	    		"copper":400,
     	    		"iron":200,
     	    		"aluminium":9600,
     	    		"silicon":1800,
     	    		"uranium":6400,
     	    		"nitrogen":1600,
     	    		"hydrogen":800
        	      },{
       	            "name": "kevlar_vest",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 24,
     	    		"shield": 2300,
     	    		"launch": 3200,
     	    		"agility":-12,
     	    		"upkeep":10,
     	    		"time":2118,
     	    		"titanium":0,
     	    		"copper":400,
     	    		"iron":200,
     	    		"aluminium":6400,
     	    		"silicon":1534,
     	    		"uranium":5334,
     	    		"nitrogen":1334,
     	    		"hydrogen":800
        	      },{
       	            "name": "power_vest",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 24,
     	    		"shield": 2600,
     	    		"launch": 4320,
     	    		"agility":-15,
     	    		"upkeep":10,
     	    		"time":2180,
     	    		"titanium":0,
     	    		"copper":400,
     	    		"iron":200,
     	    		"aluminium":9600,
     	    		"silicon":1800,
     	    		"uranium":7200,
     	    		"nitrogen":1600,
     	    		"hydrogen":800
        	      },{
       	            "name": "power_armor",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 26,
     	    		"shield": 2900,
     	    		"launch": 4808,
     	    		"agility":-16,
     	    		"upkeep":10,
     	    		"time":2324,
     	    		"titanium":0,
     	    		"copper":400,
     	    		"iron":200,
     	    		"aluminium":10400,
     	    		"silicon":1840,
     	    		"uranium":8800,
     	    		"nitrogen":1600,
     	    		"hydrogen":800
        	      },{
       	            "name": "nano_helmet",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 26,
     	    		"shield": 2900,
     	    		"launch": 4808,
     	    		"agility":-16,
     	    		"upkeep":10,
     	    		"time":2324,
     	    		"titanium":0,
     	    		"copper":400,
     	    		"iron":200,
     	    		"aluminium":10400,
     	    		"silicon":1840,
     	    		"uranium":8800,
     	    		"nitrogen":1600,
     	    		"hydrogen":800
        	      },{
       	            "name": "armosore",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 29,
     	    		"shield": 4000,
     	    		"launch": 6568,
     	    		"agility":-18,
     	    		"upkeep":10,
     	    		"time":1249,
     	    		"titanium":0,
     	    		"copper":400,
     	    		"iron":200,
     	    		"aluminium":13600,
     	    		"silicon":2374,
     	    		"uranium":13334,
     	    		"nitrogen":2134,
     	    		"hydrogen":800
        	      },{
       	            "name": "nano_armor",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 31,
     	    		"shield": 400,
     	    		"launch": 6568,
     	    		"agility":-20,
     	    		"upkeep":10,
     	    		"time":1249,
     	    		"titanium":0,
     	    		"copper":400,
     	    		"iron":200,
     	    		"aluminium":13600,
     	    		"silicon":2374,
     	    		"uranium":13334,
     	    		"nitrogen":2134,
     	    		"hydrogen":800
        	      },{
       	            "name": "nano_vest",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 31,
     	    		"shield": 3900,
     	    		"launch": 6248,
     	    		"agility":-19,
     	    		"upkeep":10,
     	    		"time":2721,
     	    		"titanium":0,
     	    		"copper":400,
     	    		"iron":200,
     	    		"aluminium":12800,
     	    		"silicon":2374,
     	    		"uranium":12534,
     	    		"nitrogen":2134,
     	    		"hydrogen":800
        	      },{
       	            "name": "ganzkorper_reflektor",
     	            "image": "/img/engine/standard_engine.gif",
     	            "size": 31,
     	    		"shield": 4700,
     	    		"launch": 13136,
     	    		"agility":-22,
     	    		"upkeep":10,
     	    		"time":2498,
     	    		"titanium":0,
     	    		"copper":800,
     	    		"iron":400,
     	    		"aluminium":27200,
     	    		"silicon":4747,
     	    		"uranium":26667,
     	    		"nitrogen":4267,
     	    		"hydrogen":1600
        	      }
        	    ],
       "accuracy": [
        	  {
        	        "name": "binocular",
        	        "image": "/img/equipment/mining_laser_prototype.gif",
        	        "size":4,
        			"accuracy": 2,
        			"upkeep":10,
        			"time":1000,
        			"titanium":5000,
        			"copper":5000,
        			"iron":0,
        			"aluminium":0,
        			"silicon":6000,
        			"uranium":0,
        			"nitrogen":0,
        			"hydrogen":7000	
        	      },{
          	        "name": "visier",
        	        "image": "/img/equipment/mining_laser_prototype.gif",
        	        "size":12,
        			"accuracy": 4,
        			"upkeep":10,
        			"time":3000,
        			"titanium":15000,
        			"copper":15000,
        			"iron":0,
        			"aluminium":0,
        			"silicon":18000,
        			"uranium":0,
        			"nitrogen":0,
        			"hydrogen":21000	
        	      },{
          	        "name": "ballistic_visier",
        	        "image": "/img/equipment/mining_laser_prototype.gif",
        	        "size":22,
        			"accuracy": 8,
        			"upkeep":10,
        			"time":9000,
        			"titanium":45000,
        			"copper":45000,
        			"iron":0,
        			"aluminium":0,
        			"silicon":48000,
        			"uranium":0,
        			"nitrogen":0,
        			"hydrogen":63000	
        	      }
        	    ],
         "capacity": [
        	  {
        	        "name": "transporter",
        	        "image": "/img/equipment/salvage_tool_prototype.gif",
        	        "size":4,
        			"cargo": 10000,
        			"upkeep":10,
        			"time":1000,
        			"titanium":1000,
        			"copper":0,
        			"iron":250,
        			"aluminium":250,
        			"silicon":334,
        			"uranium":334,
        			"nitrogen":334,
        			"hydrogen":0	
        	      },{
          	        "name": "vehicle_fleet",
        	        "image": "/img/equipment/salvage_tool_prototype.gif",
        	        "size":8,
        			"cargo": 50000,
        			"upkeep":10,
        			"time":2000,
        			"titanium":2500,
        			"copper":0,
        			"iron":2000,
        			"aluminium":500,
        			"silicon":0,
        			"uranium":0,
        			"nitrogen":0,
        			"hydrogen":0	
        	      },{
          	        "name": "magumanic_transporter_platform",
        	        "image": "/img/equipment/salvage_tool_prototype.gif",
        	        "size":8,
        			"cargo": 128000,
        			"upkeep":10,
        			"time":2800,
        			"titanium":4250,
        			"copper":450,
        			"iron":750,
        			"aluminium":1500,
        			"silicon":0,
        			"uranium":0,
        			"nitrogen":0,
        			"hydrogen":0	
        	      },{
        	        "name": "large_vehicle_fleet",
        	        "image": "/img/equipment/salvage_tool_prototype.gif",
        	        "size":10,
        			"cargo": 75000,
        			"upkeep":10,
        			"time":4000,
        			"titanium":5000,
        			"copper":0,
        			"iron":4000,
        			"aluminium":1000,
        			"silicon":0,
        			"uranium":0,
        			"nitrogen":0,
        			"hydrogen":0	
        	      },{
        	        "name": "crawler",
        	        "image": "/img/equipment/salvage_tool_prototype.gif",
        	        "size":15,
        			"cargo": 120000,
        			"upkeep":10,
        			"time":3200,
        			"titanium":3500,
        			"copper":75,
        			"iron":2700,
        			"aluminium":1700,
        			"silicon":0,
        			"uranium":0,
        			"nitrogen":25,
        			"hydrogen":0	
        	      }
	    ]
    
  }];
